package com.dashaun.cfdockercpi.setup.steps;

import com.dashaun.cfdockercpi.setup.SetupContext;
import com.dashaun.cfdockercpi.setup.SetupStep;
import com.dashaun.cfdockercpi.setup.StatusStore;
import com.dashaun.cfdockercpi.setup.StepCheck;
import com.dashaun.cfdockercpi.setup.StepResult;
import com.dashaun.cfdockercpi.setup.StepStatus;
import org.springframework.stereotype.Component;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;

@Component
public class GenerateDirectorVarsStep implements SetupStep {

    static final String NAME = "generate-director-vars";
    static final String FILE_NAME = "director-vars.yml";

    private final StatusStore statusStore;

    public GenerateDirectorVarsStep(StatusStore statusStore) {
        this.statusStore = statusStore;
    }

    @Override
    public String name() {
        return NAME;
    }

    @Override
    public String description() {
        return "Write director-vars.yml with the static BOSH director vars.";
    }

    @Override
    public StepCheck check(SetupContext ctx) {
        if (ctx.verify()) return StepCheck.NEEDS_RUN;
        Path file = ctx.stateDir().resolve(FILE_NAME);
        if (!Files.isRegularFile(file)) return StepCheck.NEEDS_RUN;
        try {
            String content = Files.readString(file);
            if (!content.contains("director_ip:")) return StepCheck.NEEDS_RUN;
            if (!content.contains("internal_cidr:")) return StepCheck.NEEDS_RUN;
        } catch (IOException e) {
            return StepCheck.NEEDS_RUN;
        }
        return StepCheck.ALREADY_DONE;
    }

    @Override
    public StepResult run(SetupContext ctx) throws IOException {
        Path file = ctx.stateDir().resolve(FILE_NAME);
        Files.createDirectories(file.getParent());
        String yaml = ""
                + "# Generated by cf-docker-cpi. Static BOSH director vars.\n"
                + "# docker_host is injected per-run at bosh invocation time (tunnel port varies).\n"
                + "director_ip: " + ctx.directorIp() + "\n"
                + "internal_cidr: " + ctx.internalCidr() + "\n";
        Files.writeString(file, yaml);

        StringBuilder log = new StringBuilder();
        log.append("Wrote ").append(file).append('\n');
        log.append(yaml);
        Path logFile = ctx.newLogFile(NAME);
        Files.createDirectories(logFile.getParent());
        Files.writeString(logFile, log.toString());

        String summary = "director_ip=" + ctx.directorIp() + " internal_cidr=" + ctx.internalCidr();
        statusStore.put(ctx.statusFile(), NAME, StepStatus.pass(summary));
        return StepResult.ran(summary + " (file: " + file + ")");
    }
}
